### ISSUE TITLE
Atualizar professores

### ISSUE THREAD

**Issue by marcospotasz** [comschool-dev/fastcommerce#10]
**Fernanda Dutra**

Especialista em Comunicação, sócia diretora da Flyflow, professora, palestrante e coach. Formada em Administração e Artes Plásticas e Pós-graduada em Gestão Estratégica de Pessoas e Marketing pela Universidade Presbiteriana Mackenzie. Possui diversos certificados profissionais, entre eles de Coaching e Gestão Estratégica em Neurobusiness.

**Elisa Malheiros**

Graduada em Comunicação Social, Pós-graduada em Comunicação com o Mercado pela ESPM e especialista em Consultoria de Imagem e Estilo (Belas Artes). Elisa possui vasto conhecimento no mercado corporativo, atuando em diversas áreas. São 12 anos de experiência nacional e Internacional, em cidades como Nova York, Barcelona e Cidade do México. Atualmente é sócia e fundadora da Emana Consultoria.

**Angela Bueno** 

Sócia e fundadora da empresa Emana Consultoria, graduada em Moda, com Pós-graduação em Moda e Estilo (SENAC). Possui Especialização em Consultoria de Imagem e Estilo, e Coloração Pessoal pela Belas Artes. Além de ministrar Workshops e palestrar sobre moda, comportamento e estilo.

**Lucimar Delarolli** 

Mestranda em Gestão do Conhecimento (Universidad de Léon-Espanha) com MBA em Gestão de Recursos Humanos na PUC-RJ. Bacharel e Licenciada em Psicologia na Universidade Gama Filho e Pós-graduada em Gestão de Pessoas, também pela PUC-RJ. Possui amplo conhecimento e mais de 25 anos de experiência em posições de Business Partner em empresas multinacionais, ONG e Consultoria, Gestão de Pessoas e em Especialização em Desenvolvimento Humano. Além de professora dos cursos de Pós-graduação nos MBAs de Marketing da ESPM e Gestão de Negócios do IBMEC.

**Felipe Magalhães Bonel**  

Profissional de tecnologia e comunicação. Formado em Multimeios pela Pontifícia Universidade Católica de São Paulo, já atou com projetos de inteligência artificial para companhias como Motorola, Gol, Nextel, Votorantim Metais e Telefônica/Vivo. É especialista em User Experience Conversacional e gestão de produtos digitais.

[
Link com as fotos](https://comschool-my.sharepoint.com/:f:/g/personal/marcos_potasz_comschool_com_br/ElpRUlTlAQZOkeCx-IQ8woEBa79udmQsmdvLKZ7_WdVhWQ?e=j4wmG8)

**Comment by ccgbon** [comment]
Faltaram:
* Title de cada pg de prof
* Subtítulo de cada prof
* Metas description
* Metas keywords
* Nome das imagens
* Alt das imagens

**Comment by marcospotasz** [comment]
Fernanda Dutra

Especialista em Comunicação, sócia diretora da Flyflow, professora, palestrante e coach. Formada em Administração e Artes Plásticas e Pós-graduada em Gestão Estratégica de Pessoas e Marketing pela Universidade Presbiteriana Mackenzie. Possui diversos certificados profissionais, entre eles de Coaching e Gestão Estratégica em Neurobusiness.

**Meta Title** Fernanda Dutra | ComSchool
**Subtítulo** Professora do Curso de Comunicação Empresarial
**Meta Description** Fernanda Dutra é Professora do Curso de Comunicação Empresarial. Cursos Comportamentais. Cursos Empresariais. Cursos Presenciais ou Online ao Vivo. Certificação reconhecida.
**Meta Keywords** Fernanda Dutra, Curso de Comunicação Empresarial
**Nome das Imagens** Fernanda_Dutra_Curso_de_Comunicacao_Empresarial.jpg
**Alt das Imagens** Fernanda Dutra | Curso de Comunicação Empresarial

Elisa Malheiros

Graduada em Comunicação Social, Pós-graduada em Comunicação com o Mercado pela ESPM e especialista em Consultoria de Imagem e Estilo (Belas Artes). Elisa possui vasto conhecimento no mercado corporativo, atuando em diversas áreas. São 12 anos de experiência nacional e Internacional, em cidades como Nova York, Barcelona e Cidade do México. Atualmente é sócia e fundadora da Emana Consultoria.

**Meta Title** Elisa Malheiros | ComSchool
**Subtítulo** Professora do Curso de Consultoria de Imagem Corporativa
**Meta Description** Elisa Malheiros é Professora do Curso de Consultoria de Imagem Corporativa. Cursos Comportamentais. Cursos Empresariais. Cursos Presenciais ou Online ao Vivo. Certificação reconhecida.
**Meta Keywords** Elisa Malheiros, Curso de Consultoria de Imagem Corporativa
**Nome das Imagens** Elisa_Malheiros_Curso_de_Consultoria_de_Imagem_Corporativa.jpg
**Alt das Imagens** Elisa Malheiros | Curso de Consultoria de Imagem Corporativa

Angela Bueno

Sócia e fundadora da empresa Emana Consultoria, graduada em Moda, com Pós-graduação em Moda e Estilo (SENAC). Possui Especialização em Consultoria de Imagem e Estilo, e Coloração Pessoal pela Belas Artes. Além de ministrar Workshops e palestrar sobre moda, comportamento e estilo.

**Meta Title** Angela Bueno | ComSchool
**Subtítulo** Professora do Curso de Consultoria de Imagem Corporativa
**Meta Description** Angela Bueno é Professora do Curso de Consultoria de Imagem Corporativa. Cursos Comportamentais. Cursos Empresariais. Cursos Presenciais ou Online ao Vivo. Certificação reconhecida.
**Meta Keywords** Angela Bueno, Curso de Consultoria de Imagem Corporativa
**Nome das Imagens** Angela_Bueno_Curso_de_Consultoria_de_Imagem_Corporativa.jpg
**Alt das Imagens** Angela Bueno | Curso de Consultoria de Imagem Corporativa

Lucimar Delarolli

Mestranda em Gestão do Conhecimento (Universidad de Léon-Espanha) com MBA em Gestão de Recursos Humanos na PUC-RJ. Bacharel e Licenciada em Psicologia na Universidade Gama Filho e Pós-graduada em Gestão de Pessoas, também pela PUC-RJ. Possui amplo conhecimento e mais de 25 anos de experiência em posições de Business Partner em empresas multinacionais, ONG e Consultoria, Gestão de Pessoas e em Especialização em Desenvolvimento Humano. Além de professora dos cursos de Pós-graduação nos MBAs de Marketing da ESPM e Gestão de Negócios do IBMEC.

**Meta Title** Lucimar Delarolli | ComSchool
**Subtítulo** Professora do Curso de Desenvolvimento de Liderança
**Meta Description**Lucimar Delarolli é Professora do Curso de Desenvolvimento de Liderança.  Cursos Comportamentais. Cursos Empresariais. Cursos Presenciais ou Online ao Vivo. Certificação reconhecida.
**Meta Keywords** Lucimar Delarolli, Curso de Desenvolvimento de Liderança
**Nome das Imagens** Lucimar_Delarolli_Curso_de_Desenvolvimento_de_Lideranca.jpg
**Alt das Imagens** Lucimar Delarolli | Curso de Desenvolvimento de Liderança

Felipe Magalhães Bonel

Profissional de tecnologia e comunicação. Formado em Multimeios pela Pontifícia Universidade Católica de São Paulo, já atou com projetos de inteligência artificial para companhias como Motorola, Gol, Nextel, Votorantim Metais e Telefônica/Vivo. É especialista em User Experience Conversacional e gestão de produtos digitais.

**Meta Title** Felipe Magalhães Bonel | ComSchool
**Subtítulo** Professor do Curso de Chatbot na Prática
**Meta Description**Felipe Magalhães Bonel é Professor do Curso de Chatbot na Prática.  Cursos de Atendimento. Cursos de Marketing Digital. Cursos Presenciais ou Online ao Vivo. Certificação reconhecida.
**Meta Keywords** Felipe Magalhães Bonel, Curso de Chatbot na Prática
**Nome das Imagens** Felipe_Magalhaes_Bonel_Curso_Chatbot_na_Pratica.jpg
**Alt das Imagens** Felipe Magalhães Bonel | Curso de Chatbot na Prática

**Comment by ccgbon** [comment]
* Redirecionamentos pendentes para `/Angela-Bueno`, `/Elisa-Malheiros`, `/Felipe-Bonel`, `/Fernanda-Dutra` e `/Lucimar-Delarolli`
* Faltou a imagem `Lucimar_Delarolli_Curso_de_Desenvolvimento_de_Lideranca.jpg`

**Comment by marcospotasz** [comment]
O subtítulo da Angela Bueno, ficou com o escrito subtítulo. 

A foto da Elisa Malheiros não está carregando. 

Redirect criado.

Vou verificar a imagem da Lucimar Delarrolli.

**Comment by ccgbon** [comment]
* Subtítulo da Angela corrigido
* Foto da Elisa corrigida

Aguardando foto da Lucimar...

**Comment by marcospotasz** [comment]
Lucimar-delaroli
![Lucimar-delaroli](https://user-images.githubusercontent.com/56686490/67883895-a01a0e00-fb23-11e9-8b1a-25de25e0a84e.png)


Segue fotos de outros professores para atualizar:
Vinicius-Mancini
![Vinicius-Mancini](https://user-images.githubusercontent.com/56686490/67884004-d9eb1480-fb23-11e9-8049-c0cd3b1ef231.jpg)
Andre-Ferracini
![Andre-Ferracini](https://user-images.githubusercontent.com/56686490/67884005-d9eb1480-fb23-11e9-9a30-18827aa9f150.jpg)
Ivan-Alves
![Ivan-Alves](https://user-images.githubusercontent.com/56686490/67884006-d9eb1480-fb23-11e9-915e-7760a515ac5a.jpg)
Pablo-Moura
![Pablo-Moura](https://user-images.githubusercontent.com/56686490/67884007-d9eb1480-fb23-11e9-976e-18b26fa1fab3.jpg)
